apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshop

resources:
- clustertasks-buildah-custom.yaml
- sign-images-pipeline-pvc.yaml
- sign-images-pipeline.yaml
- unsigned-images-pipeline.yaml
- tasks-apply-manifests.yaml
- tasks-cosign.yaml
- tasks-update-deployment.yaml
- kyverno-check-images-cluster-policy.yaml
