apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-workflow-signed
  namespace: argo
  labels:
    workflows.argoproj.io/workflow-template: ci-workflow-signed
spec:
  arguments:
    parameters:
      - name: app_repo
        value: "https://github.com/rcarrata/argocon22-app"
      - name: git_branch
        value: 'master'
      - name: container_tag
        value: 'v3-signed'
      - name: container_image
        value: "ghcr.io/rcarrata/argocon22-app"
      - name: dockerfile
        value: Dockerfile
      - name: path
        value: "k8s/"
      - name: deployment_name
        value: "argocon22-app"
      - name: namespace
        value: "argo"
  workflowTemplateRef:
    name: ci-workflow-signed